In [1]:
import pandas as pd
import numpy as np

In [2]:
# p1 = pd.read_csv("data/llama_1p.csv")
p2 = pd.read_csv("data/add_data/llama_2p.csv")
p3 = pd.read_csv("data/add_data/llama_3p.csv")
i2 = pd.read_csv("data/add_data/llama_2i.csv")
i3 = pd.read_csv("data/add_data/llama_3i.csv")
in2 = pd.read_csv("data/add_data/llama_2in.csv")
in3 = pd.read_csv("data/add_data/llama_3in.csv")
inp = pd.read_csv("data/add_data/llama_inp.csv")
pni = pd.read_csv("data/add_data/llama_pni.csv")
pin = pd.read_csv("data/add_data/llama_pin.csv")

In [3]:
# df = pd.concat([p1, p2, p3, i2, i3, in2, in3, inp, pin, pni], axis = 1)
# df

df = pd.concat([p2, p3, i2, i3, in2, in3, inp, pin, pni], axis = 1)
df

,2p_FOL,2p_FOL_NL,3p_FOL,3p_FOL_NL,2i_FOL,2i_FOL_NL,3i_FOL,3i_FOL_NL,2in_FOL,2in_FOL_NL,3in_FOL,3in_FOL_NL,inp_FOL,inp_FOL_NL,pin_FOL,pin_FOL_NL,pni_FOL,pni_FOL_NL
0,𝑞 = Y? . ∃X ∃Y: (place_of_death_was_the_place_...,What is the gender of the people who died in C...,𝑞 = Z? . ∃X ∃Y ∃Z: (organizations_founded_are_...,Who are the individuals influenced by the peer...,𝑞 = X? . ∃X : (people_with_this_degree_are_stu...,What people have degrees from both Jesus Colle...,𝑞 = X? . ∃X: (team_has_players_who_play_sports...,Which football players have played for both S....,𝑞 = X? . ∃X: (sports_team_has_colors('Pittsbur...,What are the colors of the Pittsburgh Steelers...,𝑞 = X? . ∃X: (artists_are_in_genre('Marvin Hat...,Which music genres are associated with both Ma...,𝑞 = Y? . ∃X ∃Y : ((statistical_region_has_gdp_...,What currencies were used to estimate the budg...,𝑞 = Y? . ∃X ∃Y : ((people_cause_of_death('Athl...,What influences were influenced by people who ...,𝑞 = Y? . ∃X ∃Y : ((award_category_has_winners_...,Which vacation choices of Lady Gaga did not wi...
1,𝑞 = Y? . ∃X ∃Y: (actor_is_in_performance_in_fi...,Who directed the films that feature Topaz actors?,𝑞 = Z? . ∃X ∃Y ∃Z: (film_has_executive_produce...,What are the professions of award winners who ...,𝑞 = X? . ∃X : (football_team_has_position_in_c...,What players of Chivas USA also play for AS Mo...,𝑞 = X? . ∃X: (position_s_is_held_by_players_in...,Which players in the Arizona State Sun Devils ...,𝑞 = X? . ∃X: (group_membership_is_a_regular_pe...,"What are the members of ""The Decemberists"" who...",𝑞 = X? . ∃X: (sport_is_played_by_sports_team('...,Which sports are played by both the Tokyo Yaku...,𝑞 = Y? . ∃X ∃Y : ((celebrity_has_friendship_wi...,What TV programs have celebrities who are frie...,𝑞 = Y? . ∃X ∃Y : ((program_is_program_produced...,What awards ceremonies have winners of awards ...,𝑞 = Y? . ∃X ∃Y : ((genre_is_a_genre_of_tv_prog...,Which Tony Award for Best Featured Actor in a ...
2,𝑞 = Y? . ∃X ∃Y: (award_winning_work_has_awards...,What organizations are led by winners of award...,𝑞 = Z? . ∃X ∃Y ∃Z: (person_has_nationality('Ge...,What are the types of TV programs produced by ...,𝑞 = X? . ∃X : (team_has_players_who_play_sport...,What players of Club Atlas play for 1. FC Kais...,𝑞 = X? . ∃X: (award_winner_is_an_award_winner_...,"What awards have Michael Minkler, Richard Donn...",𝑞 = X? . ∃X: (award_honor_is_awarded_to_award_...,What are the Golden Bear award-winning works t...,𝑞 = X? . ∃X: (actor_is_in_performance_in_film(...,What films feature actors from Best in Show an...,𝑞 = Y? . ∃X ∃Y : ((award_nominee_is_an_award_n...,"What films have actors nominated for awards, w...",𝑞 = Y? . ∃X ∃Y : ((adjoining_relationship_is_a...,What counties with an athlete's adjoining loca...,𝑞 = Y? . ∃X ∃Y : ((interests_are_had_by_philos...,Which philosophers who are interested in athle...
3,𝑞 = Y? . ∃X ∃Y: (award_nominee_has_multiple_aw...,What awards did Lisa Kudrow win?,𝑞 = Z? . ∃X ∃Y ∃Z: (student_is_a_graduate_of_e...,What are the majors of students who graduated ...,𝑞 = X? . ∃X : (film_has_production_companies('...,What production companies are common to both t...,𝑞 = X? . ∃X: (film_has_release_date_s_which_is...,What regions have had simultaneous releases of...,𝑞 = X? . ∃X: (person_was_born_in_place('Richar...,Who are the places where Richard Rorty was bor...,𝑞 = X? . ∃X: (film_has_release_date_that_is_a_...,What films have release dates that are regiona...,𝑞 = Y? . ∃X ∃Y : ((location_is_contained_by_lo...,What are the second-level divisions of the cou...,𝑞 = Y? . ∃X ∃Y : ((location_contains_location(...,What places that contain Athlete are founded b...,𝑞 = Y? . ∃X ∃Y : ((genre_is_a_genre_of_film('A...,Which film genres that are not associated with...
4,𝑞 = Y? . ∃X ∃Y: (location_is_contained_by_loca...,What are the film release regions with release...,𝑞 = Z? . ∃X ∃Y ∃Z: (educational_institution_ha...,What are the languages of films featuring acto...,"𝑞 = X? . ∃X : (film_has_language('Salvador', X...",What films have both Salvador and Thirteen Day...,"𝑞 = X? . ∃X: (webpage_has_category('Innocent',...",What webpages are categorized as both Innocent...,𝑞 = X? . ∃X: (person_has_profession('Donna Sum...,Who are the professions that Donna Summer had ...,𝑞 = X? . ∃X: (film_has_performance_by_actor_in...,What films featuring Geoffrey Lewis are availa...,𝑞 = Y? . ∃X ∃Y : ((award_category_has_nominees...,Who are the nominees for the Hong Kong Film Aw...,𝑞 = Y? . ∃X ∃Y : ((person_was_born_in_place('A...,What places of death are associated with athle...,𝑞 = Y? . ∃X ∃Y : ((role_is_a_track_contributio...,Which trumpet performances feature a regular g...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23995,𝑞 = Y? . ∃X ∃Y: (film_has_release_date_s_which...,What are the second-level divisions of the reg...,𝑞 = Z? . ∃X ∃Y ∃Z: (actor_is_in_performance_in...,What are the films from the countries of origi...,𝑞 = X? . ∃X : (university_has_domestic_tuition...,What is the net worth of Josh Schwartz that ma...,𝑞 = X? . ∃X: (artist_has_origin('Sonny Rollins...,In what city or town did Sonny Rollins origina...,𝑞 = X? . ∃X: (award_winning_work_has_awards_wo...,"Who are the award winners of ""Cheers"" who do n...",𝑞 = X? . ∃X: (location_is_contained_by_locatio...,What districts in Blair County were represente...,𝑞 = Y? . ∃X ∃Y : ((football_team_has_current_r...,What positions are held by the current roster ...,𝑞 = Y? . ∃X ∃Y : ((award_nominee_has_award_nom...,What athletes who have been nominated for awar...,𝑞 = Y? . ∃X ∃Y : ((military_conflict_has_comba...,Which government positions held by Ariel Sharo...
23996,𝑞 = Y? . ∃X ∃Y: (biblioness_has_bibs_location_...,What films are from Tehran?,𝑞 = Z? . ∃X ∃Y ∃Z: (sports_team_has_colors('Pr...,What are the institutions where students have ...,𝑞 = X? . ∃X : (film_has_films('Posttraumatic s...,What films about posttraumatic stress disorder...,𝑞 = X? . ∃X: (award_nominee_is_an_award_nomina...,What Primetime Emmy Awards for Outstanding Gue...,𝑞 = X? . ∃X: (location_has_time_zones('Ashtabu...,What are the time zones of Ashtabula County th...,𝑞 = X? . ∃X: (award_nominee_has_multiple_award...,Which films have both Walter Plunkett and Iren...,𝑞 = Y? . ∃X ∃Y : ((educational_institution_has...,What majors have students graduated with from ...,𝑞 = Y? . ∃X ∃Y : ((industry_is_had_by_business...,What companies employ people with the title At...,𝑞 = Y? . ∃X ∃Y : ((award_nominee_has_multiple_...,Which athletes have multiple award nominations...
23997,𝑞 = Y? . ∃X ∃Y: (place_lived_is_a_location_of_...,Who are the SNL cast members who were part of ...,𝑞 = Z? . ∃X ∃Y ∃Z: (genre_has_artists('Noise m...,What are the majors that students who are also...,𝑞 = X? . ∃X : (award_nominee_has_award_nominat...,What TV sitcoms has David Hyde Pierce been nom...,𝑞 = X? . ∃X: (award_nominee_has_multiple_award...,What awards did Jennifer Coolidge receive at t...,𝑞 = X? . ∃X: (award_winner_is_an_award_winner_...,Who are the award winners of Sammy Cahn's awar...,𝑞 = X? . ∃X: (award_is_an_award_nomination_for...,What actresses nominated for the Los Angeles F...,𝑞 = Y? . ∃X ∃Y : ((award_winner_has_awards_won...,"What awards have been won by James Levine, exc...",𝑞 = Y? . ∃X ∃Y : ((role_is_a_track_contributio...,What groups that have athletes as regular memb...,𝑞 = Y? . ∃X ∃Y : ((award_nomination_is_nominat...,Which films featuring Quincy Jones did not hav...
23998,𝑞 = Y? . ∃X ∃Y: (film_has_music('Punch-Drunk L...,What are the award categories in which the win...,𝑞 = Z? . ∃X ∃Y ∃Z: (genre_is_a_genre_of_film('...,What are the nationalities of people from the ...,𝑞 = X? . ∃X : (person_is_a_personal_appearance...,In which films has Jacob Zuma made a personal ...,𝑞 = X? . ∃X: (deceased_person_died_at_place_of...,Where did Kristen Stewart live and Joseph Gord...,𝑞 = X? . ∃X: (organization_member_is_a_member_...,What are the members of Saint Kitts and Nevis ...,𝑞 = X? . ∃X: (celebrity_is_friend_of_another_c...,What celebrities who are friends of Nicolas Ca...,𝑞 = Y? . ∃X ∃Y : ((student_is_a_graduate_of_ed...,What type of school did JoBeth Williams gradua...,𝑞 = Y? . ∃X ∃Y : ((adjoining_relationship_is_a...,What locations are adjoining to Athlete and in...,𝑞 = Y? . ∃X ∃Y : ((genre_is_a_genre_of_film('A...,Which films of the genre Athlete did not have ...
23999,𝑞 = Y? . ∃X ∃Y: (film_has_performance_by_actor...,What films directed by the directors of films ...,𝑞 = Z? . ∃X ∃Y ∃Z: (team_has_players_who_play_...,What are the current teams of football players...,𝑞 = X? . ∃X : (artist_has_origin('Ricky Nelson...,What place was Josh Sussman born in where Rick...,𝑞 = X? . ∃X: (instrument_has_instrumentalists(...,What awards have Luther Vandross won as a Musi...,𝑞 = X? . ∃X: (person_has_profession('Drake Bel...,Who are the professions of Drake Bell that are...,𝑞 = X? . ∃X: (football_team_has_current_roster...,Which football players are currently on the ro...,𝑞 = Y? . ∃X ∃Y : ((genre_is_a_genre_of_film('R...,What films nominated for Romantic fantasy that...,𝑞 = Y? . ∃X ∃Y : ((genre_is_a_genre_of_tv_prog...,What TV programs of the Athlete genre have awa...,𝑞 = Y? . ∃X ∃Y : ((award_winner_is_winner_of_a...,Which films distributed by the distributor of ...

In [4]:
# df.to_csv("data/sample_add_0007.csv", index=False, encoding="utf-8")

In [5]:
df = pd.read_csv("data/sample_add_0007.csv")

### NL preprocessing
- dummy nl 삭제
- 불필요한 줄나눔 삭제
- 불필요한 \ 삭제 및, 띄어쓰기, 콤마 정리

In [6]:
def count_lines(cell):
    if isinstance(cell, str):
        return len(cell.split("\n"))
    return cell

subQlen = df.iloc[:, 1::2].applymap(count_lines)
subQlen = subQlen.applymap(lambda x: x if x > 1 else np.nan)

/tmp/ipykernel_510681/581118329.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  subQlen = df.iloc[:, 1::2].applymap(count_lines)
/tmp/ipykernel_510681/581118329.py:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  subQlen = subQlen.applymap(lambda x: x if x > 1 else np.nan)

In [49]:
query_type = "pni_FOL_NL"

In [50]:
subQlen[query_type].dropna()

KeyError: 'ip_FOL_NL'

In [48]:
df[query_type][subQlen[query_type].dropna().index].values

array(['Which locations adjoining Hesse did Athlete not border?',
       'Which athletes got married at the location where Joan Baez works?',
       'Which athletes lived in Princeton but did not die there?',
       "Which locations hosted the 1983 NCAA Men's Division I Basketball Tournament where athletes died, but not at the location of their death?",
       "Which locations in India are not contained in the country where Athlete's biblioness has bibs?",
       'Which travel destinations have a monthly climate of May that are not contained in locations where athletes have campuses?',
       'Which places in Salt Lake City are not contained in locations adjoining Athlete?',
       'Which organizations headquartered in Athlete have a location contained in Plainfield that is not a HUD county place?',
       'Which locations in Asia have time zones but are not the headquarters of any organizations?',
       'Which counties that are the seat of Athlete do not have the same time zone as Ridgefield?',
       "Which administrative divisions in Chongqing are not administrative divisions of a country that adjoins an athlete's location?",
       'Which TV programs on CBS did not feature actors who have won awards honoring athletes?',
       'Which cities are headquarters of the University of North Dakota but are not places in Hud County and contain athletes?',
       'Which awards did Matt Damon win that are not won by actors who starred in Athlete?',
       'Which places where Owen Wilson has been nominated for multiple awards are not associated with places where athletes live?',
       'Which capitals are the capitals of administrative divisions that do not contain Athlete, Arizona, but have a place called Athlete that is part of Hud County?',
       "Which films that have a prequel to 'Athlete' are not of the same genre as 'High Anxiety'?",
       'Which films with a sound editor from GB were not released in a region that partially contains Athlete?',
       'Which athletes lived in places that are associated with George Washington but not with user_tsegaran_random?',
       'Which films with regional release dates in Annie did not originate from the country where the TV program Athlete is from?',
       'Which counties in Kanawha County are not capitals of administrative divisions that have an athlete as a place?',
       'Which BAFTA Academy Fellowship Award winners are athletes who are not married?',
       'Which celebrities have been cuddled with by Paris Hilton at a place where a film featuring an athlete was shot, but not at a place where the athlete lived?',
       'Which counties that adjoin Hampshire County did not have Athlete as a county seat?',
       'What are the locations where athletes who have spouses got married, but were not born?',
       'In which regions did the film "Beasts of the Southern Wild" have a regional release date, but the athlete was not exported to?',
       "Which counties do not have Gonzaga University contained within them and are not the capital of an athlete's administrative division?",
       'Which capitals in Saxony are not located in the states where athletes have bibs?',
       'Which counties adjacent to Athlete have a place called Salem but are not the seat of a US county?',
       'Which athletes of Romanian ethnicity do not have gardening hints in their Data World profile?',
       'What areas in the United States, where the headquarters of Athlete is located, are not contained in the areas measured by the United States Department of Housing and Urban Development for estimating the number of mortgages in HUD foreclosure?',
       'Which athletes were born in places that are not contained within the locations involved in the Mongol conquests?',
       'Which military conflicts involving the Kingdom of Bulgaria did not involve athletes as combatants?',
       'Which vacation choices of Barack Obama are not located in the countries where Athlete is the capital?',
       'Which travel destinations have a climate in September that are not capitals of countries where athletes have fought in conflicts?',
       'Which places adjoining Boulder County are not counties where athletes are from?',
       'What locations adjoining Manitoba did not contain Athlete?',
       'Which marriage ceremonies were held in places that are not the hometowns of athletes?',
       'Which educational institutions with crimson as one of their colors have an athlete with domestic tuition in a currency that is not associated with their endowment?',
       'Which film releases did Shia LaBeouf receive award nominations for that are not associated with the locations where Athlete events take place?',
       'Which places in Bay City are not contained in the locations adjoining Athlete?',
       'Which counties have Provo as their county seat but do not adjoin Athlete?',
       'Which Kansas-adjacent locations had athletes who held government positions but did not have representatives in the government from those locations?',
       "Which places has Ben Stiller lived at that are not contained in the locations of campuses of Athlete's educational institutions?",
       'Which counties did the Oregon Ducks football team not have a place in that is the capital of an administrative division where an athlete is from?',
       'Which films with a sound mixer crew role are not classified under genres related to athletes?',
       'Which awards has Ken Loach been nominated for that are not associated with the birthplaces of athletes?',
       'Which individuals with the same gender as Brad Dourif were combatants in a military conflict that involved athletes?',
       "Which cities has Joni Mitchell lived in that are not contained in the locations of Athlete's headquarters?",
       'Which locations adjoining Lake Michigan did athletes not have bibs in?',
       'Which burial places where Keith Moon was buried did not have actors who played athletes in films?',
       'Which places has Ginger Rogers lived at that are not counties and are contained in Athlete?',
       'What awards did Charlton Heston win that were not won by athletes who died from the same cause as the athletes who won them?',
       "Which administrative areas adjoining Brandenburg do not have 'Athlete' as a religion with a specified percentage?",
       'Which domestic partnerships did athletes who composed music for the film "Athlete" have their ceremonies in places they didn\'t live in?',
       'Which films featuring Douglas MacArthur did not have locations where Athlete performed?',
       'Which locations that adjoin Athlete also contain Monmouth County but are not in Hud County?',
       'Which places has Aretha Franklin lived at that are not places where athletes have vacationed?',
       'Which award winners of the National Society of Film Critics Award for Best Supporting Actor were not born in the same location as athletes?',
       'Which Library of Congress Classification taxonomy entries are related to athletes but do not have biblioness locations in a specific state?',
       'Which events in Iraq did not involve athlete groups that were combatants in a military conflict?',
       'Which administrative areas have Perugia as their capital and are not located in the country of athletes that are divided into second-level divisions?',
       'Where did athletes who died in Modesto die?',
       'Which Fortune Global 500 companies were founded by organizations that have an athlete as a service location of their phone number?',
       'Which military combatant groups, other than the Landgraviate of Hesse-Kassel, had athletes as members who were based in a state where the Biblioness had bibs?',
       'Which locations where athletes are present are not capitals of administrative divisions that adjoin Butler County?',
       'Which deceased persons who had Athlete as their place and did not live in Rancho Mirage, were they from?',
       "Which administrative divisions in China are not contained in the location of an athlete's capital?",
       'Which countries that have Athlete as their capital do not share a border with East Prussia?',
       'What are the locations where athletes were buried that are not contained within the locations where people who got married had their ceremonies?',
       'Which awards did people who were influenced by athletes but did not win awards honoring those athletes, and died of cancer?',
       'Which locations are locations of events in Louisville but not of events where Athlete is the capital?',
       'Which marriages took place in locations that are not capitals of countries where athletes are from?',
       'Which regions that have athletes with a certain percentage of the population adjoining Maryland did not adjoin another location?',
       'In which places did Basil Rathbone die that are not the birthplaces of athletes who have been nominated for an award?',
       'Which awards did Sunny Deol win that were not nominated for by actors in the film Athlete?',
       'Which actors from The Fast and the Furious: Tokyo Drift have lived in places where athletes have lived but have not been nominated for multiple awards?',
       'Which vacation spots did Orlando Bloom visit that are not preferred by athletes who are capitals of administrative divisions?',
       'Which locations in Aisne did not contain the locations where athletes happened?',
       'Which locations adjoining Weber County did not have Athlete as their capital?',
       'Which places that are not contained in Ocean County are adjacent to Ocean County and have an athlete as a place?',
       'Which friends of Eugene Levy lived in places where athletes died?',
       'What locations that are contained by Athlete but are not adjacent to locations where World War II happened?',
       'Which locations that adjoin Washington County are not adjacent to the capital of the administrative division of an athlete?',
       "Which films of the genre Athlete did Jane Wyman's spouse get married at the location of the ceremony, but were not filmed at those locations?",
       "Which locations in Burlington did not adjoin Athlete and have a bibliophile's book collection?",
       'Which locations that contain Nottinghamshire did not contain the location where the athlete event happened?',
       'Where did Thomas Jefferson die that is not the location of bibliophile bibliophiles from states with a high percentage of athletes?',
       'Which leaders of the New England Conservatory of Music are not office holders in the jurisdiction of Athlete?',
       'Which journalists who are also athletes have been nominated for awards but do not have personal appearances in films?',
       'Which places adjoining Siskiyou County are not capitals of administrative divisions where athletes are from?',
       'Which Academy Award for Best Actor in a Supporting Role winners were born in a place that is not a location associated with the athlete?',
       'Which locations in Palm Beach County did Athlete, who had multiple award nominations, not die at?',
       'In which places did Jack Nicholson live that are not in the same state as the locations of Athlete county places?',
       "Which travel destinations that have a monthly climate similar to Frankfurt's did not have a climate featured in the film Athlete?",
       'Which places has Vernor Vinge lived at that are not located in the counties of the capitals of administrative divisions where athletes are from?',
       'Which counties that are not adjacent to Athlete have a adjoining relationship with Lee County?',
       'Which educational institutions, like Transylvania University, have campuses at locations where athletes are present but do not contain those locations?',
       'Which places has Joe Biden lived at that are not capitals of administrative divisions where athletes are from?',
       'Which travel destinations have an October climate and are not located in the campus of an educational institution that houses athletes?',
       'Which locations containing Clearwater are not capitals of administrative divisions where athletes are from?',
       'Which Bates College campuses are not located in the same state as the location of athletes who have bibs?',
       'Which Golden Globe Award for Best Original Score winners lived in places where athletes died?',
       "Which films with an estimated budget in the same currency as the endowments of educational institutions that have athlete types did not have their endowments in the currency of the budget of 'The Passion of the Christ'?",
       'Which travel destinations have a climate in September that are not located in countries where the film "Athlete" was released?',
       'Which locations containing Panjab University, Chandigarh are not capitals of administrative divisions where Athlete is the capital?',
       'What locations where athletes happen that do not have the same time zones as Salt Lake City?',
       'Which locations in Austin are not locations of an event that contains an athlete?',
       'Which places where Charles Dickens was buried did athletes not get buried at?',
       'Which private schools did athletes hold government positions in, but were not led by leaders of organizations that they were affiliated with?',
       'Which Star Wars awards were won by actors who starred in films with no production design?',
       'Which military groups that were involved in conflicts with the Soviet Union did not have combatants from Athlete?',
       'Which locations that are not adjacent to the headquarters of Athlete are contained by Weber State University?',
       'Which films with a regional release date in "In the Name of the Father" were not exported to places adjoining Athlete?',
       'In which cities has Shohreh Aghdashloo lived that are not contained in the locations of the headquarters of athletes?',
       "Which locations did the 1985 NCAA Men's Division I Basketball Tournament take place at that are not contained within the locations where athletes are from?",
       'Which locations in Sudan do not have a capital that is adjacent to Athlete?',
       'Which educational institutions that have the same colors as Keio University do not have Athlete as a gardening hint?',
       "Which locations in California are adjacent to an athlete's location but do not have a place in Hud County?",
       'Where did Danny Kaye get married that is not a county in the location where Athlete is contained?',
       'Which organizations founded by Jesus Christ did not have an athlete as a winner of an award who also had a religion?',
       'Which travel destinations have a climate similar to New York City but are not the place of death of any athlete?',
       'Which TV programs with New Line Cinema award nominations did not have Athlete as a regular cast member?',
       'Which burial places, contained within Athlete, are not the burial places of deceased individuals buried at Windsor Castle?',
       'Which cities are the headquarters of athletes but are not contained in Sapporo?',
       'Which athletes were involved in military conflicts but not in events located in Ukraine?',
       'Which award categories did Athlete win at the 65th Tony Awards, but not in categories where they were honored?',
       "Which films, which are not from the same country as the film 'ParaNorman', have a preceding version that is an athlete-themed film?",
       'Which locations that are associated with athletes but do not have time zones also have Charlottetown as a location with time zones?',
       'Which places in Scottsdale did athletes die at, excluding those that are also a HUD county place?',
       "Which currencies are used by Loyola Marymount University's endowment but not used to report the GDP per capita of regions containing Athlete?",
       'Which Ottoman wars in Europe involved athletes who were not combatants in military conflicts?',
       "Which counties that are not adjacent to Athlete's county seat are adjacent to Anne Arundel County?",
       'Which awards in the Athlete category has Jason Reitman been influenced by, but not nominated for?',
       'Which films with the genre "Athlete" did not feature actors who won awards at the 15th Screen Actors Guild Awards?',
       'Which countries in Orange County did not have the headquarters of organizations associated with Athlete fraternities and sororities?',
       'Which places in Naperville are not adjacent to Athlete?',
       'Which films, including "Heartbeats", had a regional debut at a venue that does not adjoin a location where athletes are from and has a release date in a time zone of that location?',
       'Which awards did Sophia Loren win that were not associated with the ethnicity of athletes?',
       'Which films did Candice Bergen date participants in, but did not feature actors who were also athletes?',
       'Which marriage ceremonies took place in locations that are not contained within Athlete and are held by people who have unions of this type?',
       'Which films directed by Athlete have a bibliographic location in Lausanne but do not have a regional release date in that region?',
       'Which films were released in America but not in the location of Athlete?',
       'Which Macquarie University campuses are not located in the same place as athletes who held government positions?',
       'Which cities adjoin the City of London and are not contained in the headquarters location of Athlete organizations?',
       'Which locations adjoining Orange County did Athlete not have an adjoining relationship with?',
       'Which government positions held by Jacob Zuma were not held by officeholders in the jurisdiction of the capital of Athlete?',
       'Which locations are capitals of administrative divisions that are not adjacent to Lake County?',
       'Which athletes died in Santa Monica but did not live there?',
       'Which phone numbers of Sony Computer Entertainment have a service language that is not associated with films featuring athletes who were nominated for an Athlete award?',
       "Which counties did Eugene O'Neill die in that are not the seats of US counties where athletes are from?",
       'Which influences of Harold Pinter did not influence athletes who have won awards in the Athlete category?',
       'Which counties that have an athlete as their seat do not adjoin Oneida County?',
       'Which capitals of administrative divisions are not places in Athlete that are had by Maricopa County?',
       'Which locations that adjoin Oak Park did Athlete not live in?',
       'Which places of death are associated with Basil Rathbone but not with athletes who are peers of Athlete?',
       'Which locations that adjoin Sonora are not contained within any locations that are adjacent to an athlete?',
       "What profession does Savannah Guthrie have that is not held by athletes who got married at the location of their spouse's ceremony?",
       'Which locations adjoining Cape May County do not have an adjoining relationship with an athlete?',
       'Which marriages took place in locations that adjoin the location of athletes, but do not have bibs in the same state?',
       'Which locations adjoining Warren County are not adjacent to the capitals of administrative divisions where athletes are from?',
       'Which places has Johann Wolfgang von Goethe lived at that are not adjacent to places where athletes have lived?',
       'Which locations adjoining Athlete are not contained within Washington County?',
       'Which countries in Bhutan are not the location of the headquarters of any athletic organizations?',
       "What locations hosted the 1980 NCAA Men's Division I Basketball Tournament that are not in the same place as the capitals of administrative divisions where athletes are from?",

In [47]:
# df.loc[:, query_type] = df.loc[:, query_type].apply(lambda x: x.replace("\n\n", ' / ') if isinstance(x, str) else x)
df.loc[:, query_type] = df.loc[:, query_type].apply(lambda x: x.replace("Here is the natural language query:\n\n", '') if isinstance(x, str) else x)
df.loc[:, query_type] = df.loc[:, query_type].apply(lambda x: x.replace("Here is the converted natural language query:\n\n", '') if isinstance(x, str) else x)
# df.loc[:, query_type] = df.loc[:, query_type].apply(lambda x: x.replace("Sub-queries:\n", '') if isinstance(x, str) else x)
df.loc[:, query_type] = df.loc[:, query_type].apply(lambda x: x.replace("\n", '') if isinstance(x, str) else x)
# df.loc[:, query_type] = df.loc[:, query_type].apply(lambda x: x.replace(",,", ',') if isinstance(x, str) else x)

In [ ]:
# df.loc[:, query_type] = df.loc[:, query_type].apply(lambda x: x.replace("\"", '').replace('\\', '').replace(" ,", ",").replace(",", ", ").replace("  ", " ") if isinstance(x, str) else x)

In [51]:
# df.to_csv("data/sample_add_0007.csv", index=False, encoding='utf-8')

### 3in pni 데이터 교체

In [27]:
nl = pd.read_csv("data/llm-70B-237_FOL2NL_train.csv")
nl.head()

/tmp/ipykernel_3879550/230409728.py:1: DtypeWarning: Columns (10,11,12,13,14,15,16,17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  nl = pd.read_csv("data/llm-70B-237_FOL2NL_train.csv")

,1p,1p_FOL_NL,2p_FOL,2p_FOL_NL,3p_FOL,3p_FOL_NL,2i_FOL,2i_FOL_NL,3i_FOL,3i_FOL_NL,2in_FOL,2in_FOL_NL,3in_FOL,3in_FOL_NL,inp_FOL,inp_FOL_NL,pin_FOL,pin_FOL_NL,pni_FOL,pni_FOL_NL
0,"('Howard Hughes', ('breakup_is_participated_by...",Who did Howard Hughes participate in a breakup...,𝑞 = Y? . ∃X ∃Y: (place_lived_is_a_location_of_...,Who are the award nominees nominated by Franklin?,𝑞 = Z? . ∃X ∃Y ∃Z: (award_winner_is_winner_of_...,What are the award nominations for the categor...,𝑞 = X? . ∃X : (disciplines_or_subjects_are_a_d...,What awards in the category of Literature has ...,𝑞 = X? . ∃X: (profession_is_had_by_person('Tel...,What awards have Jennifer Celotta won that Ang...,𝑞 = X? . ∃X: (actor_is_in_performance_in_film(...,Who are the actors in Rango who have not dated...,𝑞 = X? . ∃X: (film_has_performance_by_actor_in...,What films featuring Helen Mirren are availabl...,𝑞 = Y? . ∃X ∃Y : ((medicine_has_notable_people...,What awards have been won by notable people wi...,𝑞 = Y? . ∃X ∃Y : ((netflix_genre_has_titles('H...,What films distributed from Hong Kong genres a...,𝑞 = Y? . ∃X ∃Y : ((user_has_default_domain_for...,Which biathlon events were part of the 1948 Wi...
1,"('Will Arnett', ('actor_in_regular_tv_appearan...",What TV programs is Will Arnett a regular cast...,𝑞 = Y? . ∃X ∃Y: (performance_role_has_track_pe...,What are the gardening hints related to the tr...,𝑞 = Z? . ∃X ∃Y ∃Z: (film_has_performance_by_ac...,What are the major fields of study for people ...,𝑞 = X? . ∃X : (artists_are_in_genre('John Foge...,What genres related to Soft rock is John Foger...,𝑞 = X? . ∃X: (sport_is_played_by_sports_team('...,Which football teams has Chris Waddle played f...,𝑞 = X? . ∃X: (actor_is_in_performance_in_film(...,Who are the actors in Wild at Heart who have n...,𝑞 = X? . ∃X: (award_honor_ceremony_has_winners...,What awards were won at the 41st Annual Grammy...,𝑞 = Y? . ∃X ∃Y : ((award_honor_ceremony_has_wi...,Who are the winners of the 55th Primetime Emmy...,𝑞 = Y? . ∃X ∃Y : ((nationality_is_held_by_pers...,Which athletes from the United States are not ...,𝑞 = Y? . ∃X ∃Y : ((category_is_a_category_of_w...,Which awards has Ann Curry been nominated for ...
2,"('National Treasure', ('prequel_is_a_preceding...",What are the prequels to the film National Tre...,𝑞 = Y? . ∃X ∃Y: (award_honor_is_awarded_to_awa...,What TV programs feature personal appearances ...,𝑞 = Z? . ∃X ∃Y ∃Z: (team_is_in_sports_team_ros...,What are the specializations within the profes...,𝑞 = X? . ∃X : (instrument_has_instrumentalists...,What composers are also guitar instrumentalists?,𝑞 = X? . ∃X: (adjoining_relationship_is_adjoin...,What locations in the Netherlands adjoin both ...,𝑞 = X? . ∃X: (people_cause_of_death('Pneumonia...,Who are the people whose cause of death was pn...,𝑞 = X? . ∃X: (genre_is_a_genre_of_film('Biogra...,What Biographical films are available in the U...,𝑞 = Y? . ∃X ∃Y : ((tv_producer_has_programs_pr...,What awards have programs produced by Manny Co...,𝑞 = Y? . ∃X ∃Y : ((artist_has_origin('Everythi...,What larger locations contain places related t...,𝑞 = Y? . ∃X ∃Y : ((olympics_olympic_athlete_af...,Which sports teams based in Dallas did not par...
3,"('Bonnie Raitt', ('artists_are_in_genre',))",What music genres is Bonnie Raitt associated w...,𝑞 = Y? . ∃X ∃Y: (combatants_are_members_of_mil...,What events involved members of the Empire of ...,𝑞 = Z? . ∃X ∃Y ∃Z: (hud_foreclosure_area_has_e...,What are the ethnicities of the founders of or...,"𝑞 = X? . ∃X : (gender_is_had_by_person('Male',...",What males have been nominated for multiple aw...,𝑞 = X? . ∃X: (film_is_produced_by_film('Gary G...,"What films have Gary Goetzman produced, with m...",𝑞 = X? . ∃X: (record_label_has_artist('Island ...,Which artists have been signed to Island Recor...,𝑞 = X? . ∃X: (country_has_film('United States ...,What films produced by Mark Johnson are availa...,𝑞 = Y? . ∃X ∃Y : ((tv_program_has_regular_cast...,What places were the regular cast members of D...,𝑞 = Y? . ∃X ∃Y : ((award_nominee_has_multiple_...,What awards did Samuel M. Comer's nominees win...,𝑞 = Y? . ∃X ∃Y : ((actor_is_in_performance_in_...,Which actors from A Beautiful Mind do not have...
4,"('Billy Boyd', ('person_has_profession',))",What is Billy Boyd's profession?,𝑞 = Y? . ∃X ∃Y: (citytown_is_mailing_address_o...,In which states or provinces are the headquart...,𝑞 = Z? . ∃X ∃Y ∃Z: (organization_extra_has_pho...,What is the domestic tuition fee in a specific...,𝑞 = X? . ∃X : (taxonomy_entry_is_a_taxonomy_su...,What Library of Congress Classification subjec...,𝑞 = X? . ∃X: (taxonomy_entry_is_a_taxonomy_sub...,What profession did Warren G. Harding have in ...,𝑞 = X? . ∃X: (form_of_government_is_had_by_cou...,Which countries have a unitary system of gover...,𝑞 = X? . ∃X: (award_category_has_winners_who_a...,Which Irish American actors have won the Prime...,𝑞 = Y? . ∃X ∃Y : ((film_has_release_date_s_whi...,In which administrative regions were Bridesmai...,𝑞 = Y? . ∃X ∃Y : ((producer_type_is_had_by_tv_...,What TV personalities who have made regular ap...,𝑞 = Y? . ∃X ∃Y : ((taxonomy_entry_is_a_taxonom...,Which actors in the film Austin Powers: Intern...

In [43]:
df["pni_FOL"][8]

"𝑞 = Y? . ∃X ∃Y : ((award_nomination_is_nominated_for_award('The Talented Mr. Ripley', X) ∧ ¬film_distributor_has_films_distributed_which_are_related_to_film_film_distributor_relationship(X, Y?)) ∧ netflix_genre_has_titles('Romance Film', Y?))"

In [44]:
nl["pni_FOL"][8]

"𝑞 = Y? . ∃X ∃Y : ((award_nomination_is_nominated_for_award('The Talented Mr. Ripley', X) ∧ ¬film_distributor_has_films_distributed_which_are_related_to_film_film_distributor_relationship(X, Y?)) ∧ netflix_genre_has_titles('Romance Film', Y?))"

In [40]:
# df = pd.read_pickle("data/FB15k-237-betae/train-queries.pkl")
# df

In [43]:
types = list(df.keys())

original = pd.DataFrame()
for key in df.keys():
    df[key]
    added = pd.DataFrame(list(map(str, list(df[key]))))
    original = pd.concat([original, added], axis = 1)

original.columns = ['1p','2p','3p','2i','3i','2in','3in','inp','pin','pni']
original

,1p,2p,3p,2i,3i,2in,3in,inp,pin,pni
0,"(3793, (107,))","(4582, (133, 17))","(4526, (95, 364, 39))","((5588, (135,)), (3239, (95,)))","((1730, (35,)), (2669, (7,)), (3587, (17,)))","((135, (13,)), (8594, (154, -2)))","((2263, (12,)), (1080, (57,)), (3352, (4, -2)))","(((1306, (298,)), (954, (49, -2))), (25,))","((2410, (4, 65)), (592, (167, -2)))","((4157, (348, 208, -2)), (389, (131,)))"
1,"(6290, (3,))","(3154, (150, 456))","(11341, (12, 5, 225))","((5179, (41,)), (5027, (104,)))","((344, (161,)), (117, (11,)), (5147, (340,)))","((9891, (13,)), (7862, (155, -2)))","((1285, (21,)), (2192, (365,)), (8219, (21, -2)))","(((6805, (21,)), (1641, (15, -2))), (20,))","((32, (97, 80)), (13643, (80, -2)))","((62, (51, 121, -2)), (548, (17,)))"
2,"(3725, (461,))","(7364, (61, 375))","(2273, (341, 34, 362))","((138, (84,)), (1415, (35,)))","((12649, (117,)), (10511, (116,)), (1046, (30,)))","((5983, (100,)), (871, (35, -2)))","((6607, (63,)), (32, (57,)), (1854, (211, -2)))","(((11855, (290,)), (11210, (4, -2))), (60,))","((1529, (320, 31)), (1124, (174, -2)))","((2864, (209, 161, -2)), (5445, (188,)))"
3,"(8965, (41,))","(6187, (263, 176))","(13948, (240, 453, 143))","((141, (87,)), (491, (16,)))","((645, (169,)), (4161, (233,)), (367, (219,)))","((4215, (152,)), (1271, (269, -2)))","((32, (57,)), (6438, (169,)), (4130, (25, -2)))","(((1242, (2,)), (14132, (49, -2))), (48,))","((2477, (16, 6)), (1327, (79, -2)))","((159, (13, 90, -2)), (8556, (2,)))"
4,"(2489, (34,))","(10789, (167, 286))","(372, (226, 88, 332))","((774, (237,)), (11041, (119,)))","((774, (237,)), (12645, (34,)), (8360, (92,)))","((4494, (1,)), (6473, (443, -2)))","((1974, (94,)), (1253, (142,)), (4626, (2, -2)))","(((26, (26,)), (190, (437, -2))), (125,))","((494, (183, 375)), (173, (13, -2)))","((774, (237, 97, -2)), (4448, (13,)))"
...,...,...,...,...,...,...,...,...,...,...
149684,"(647, (164,))","(2654, (28, 103))","(8050, (94, 16, 50))","((7202, (13,)), (9201, (91,)))","((32, (27,)), (657, (4,)), (249, (213,)))",NaN,NaN,NaN,NaN,NaN
149685,"(3006, (194,))","(3892, (56, 59))","(11046, (263, 326, 177))","((90, (69,)), (441, (173,)))","((2438, (309,)), (5911, (254,)), (32, (411,)))",NaN,NaN,NaN,NaN,NaN
149686,"(2378, (56,))","(5573, (65, 38))","(11957, (86, 459, 298))","((2424, (35,)), (967, (35,)))","((90, (439,)), (208, (271,)), (90, (279,)))",NaN,NaN,NaN,NaN,NaN
149687,"(9075, (91,))","(9543, (48, 380))","(5787, (86, 459, 433))","((393, (35,)), (434, (171,)))","((141, (87,)), (3414, (39,)), (6489, (49,)))",NaN,NaN,NaN,NaN,NaN
149688,"(8881, (95,))","(13619, (240, 50))","(13069, (78, 407, 5))","((3483, (12,)), (32, (57,)))","((2885, (162,)), (13198, (30,)), (2885, (163,)))",NaN,NaN,NaN,NaN,NaN

In [110]:
text_org = pd.read_csv("data/llm-70B-237_FOL2NL_test.csv")
text_org.head(5)

,1p_FOL,1p_FOL_NL,2p_FOL,2p_FOL_NL,3p_FOL,3p_FOL_NL,2i_FOL,2i_FOL_NL,3i_FOL,3i_FOL_NL,...,pni_FOL,pni_FOL_NL,ip_FOL,ip_FOL_NL,pi_FOL,pi_FOL_NL,2u_FOL,2u_FOL_NL,up_FOL,up_FOL_NL
0,𝑞 = X? . ∃X: (educational_institution_has_stud...,What majors do students graduate with from Wes...,𝑞 = Y? . ∃X ∃Y: (adjoining_relationship_is_adj...,What countries have bibs in locations adjoinin...,𝑞 = Z? . ∃X ∃Y ∃Z: (disease_has_risk_factors('...,What sports teams do professional athletes who...,𝑞 = X? . ∃X : (nationality_is_held_by_person('...,Who are the individuals from the United States...,𝑞 = X? . ∃X: (organization_has_child_which_is_...,What subsidiaries of Bandai Namco Holdings hav...,...,𝑞 = Y? . ∃X ∃Y : ((person_has_profession('Walt...,What films were released on video that Walter ...,𝑞 = Y? . ∃X ∃Y : ((sports_are_part_of_olympic_...,Which countries have participated in the Olymp...,𝑞 = Y? . ∃X ∃Y : ((location_contains_location(...,Which actors are buried in a place of burial l...,𝑞 = X? . ∃X : (deceased_person_died_at_place_o...,What places are either where Robert L. Surtees...,𝑞 = Y? . ∃X ∃Y : ((award_winner_has_awards_won...,What films have performances by actors who hav...
1,𝑞 = X? . ∃X: (film_film_distributor_relationsh...,"What companies distributed the film ""Zookeeper""?",𝑞 = Y? . ∃X ∃Y: (risk_factors_are_factors_of_d...,What are the symptoms of the risk factors of P...,𝑞 = Z? . ∃X ∃Y ∃Z: (taxonomy_entry_is_a_taxono...,Who are the peers of the peers influenced by t...,𝑞 = X? . ∃X : (award_winner_is_winner_of_award...,What awards have both James Cagney and Johnny ...,𝑞 = X? . ∃X: (award_nominee_is_an_award_nomina...,What films has Taraji P. Henson been nominated...,...,𝑞 = Y? . ∃X ∃Y : ((currency_is_used_for_net_wo...,Which films distributed by Paramount Pictures ...,𝑞 = Y? . ∃X ∃Y : ((team_is_participating_in_sp...,What sports leagues have teams that are regist...,𝑞 = Y? . ∃X ∃Y : ((taxonomy_entry_is_a_taxonom...,What people born in New York City have nationa...,𝑞 = X? . ∃X : (netflix_genre_has_titles('Comed...,What titles on Netflix are either classified u...,𝑞 = Y? . ∃X ∃Y : ((film_crew_role_is_a_film_cr...,Who are the executive producers of films that ...
2,𝑞 = X? . ∃X: (student_is_a_graduate_of_educati...,What educational institutions did Dinah Shore ...,𝑞 = Y? . ∃X ∃Y: (genre_is_a_genre_of_tv_progra...,What awards are soap opera TV programs nominat...,𝑞 = Z? . ∃X ∃Y ∃Z: (travel_destination_monthly...,Who are the people who practice the religions ...,𝑞 = X? . ∃X : (artists_are_in_genre('Dir En Gr...,What genres are both Dir En Grey and Brendon S...,𝑞 = X? . ∃X: (award_ceremony_has_awards_presen...,"Which artists from Austin, who are keyboard pl...",...,𝑞 = Y? . ∃X ∃Y : ((administrative_area_has_adm...,Which film producers from Greater London do no...,𝑞 = Y? . ∃X ∃Y : ((award_category_has_category...,"What awards are in the category of the ""Grammy...",𝑞 = Y? . ∃X ∃Y : ((celebrity_is_friend_of_anot...,In what places in the Eastern Time Zone have f...,𝑞 = X? . ∃X : (award_winner_has_awards_won_who...,What awards did Greg Daniels win or what peopl...,𝑞 = Y? . ∃X ∃Y : ((team_is_in_sports_team_rost...,Which teams are the current teams of football ...
3,𝑞 = X? . ∃X: (award_is_an_award_nomination_for...,What works were nominated for the Hugo Award f...,𝑞 = Y? . ∃X ∃Y: (award_category_has_nominees_w...,What films are subjects of the nominees for th...,𝑞 = Z? . ∃X ∃Y ∃Z: (award_honor_ceremony_has_w...,What films are distributed by distributors rel...,𝑞 = X? . ∃X : (profession_is_had_by_person('Pr...,Who are the Prime Ministers of Canada?,𝑞 = X? . ∃X: (category_is_a_category_of_webpag...,What official websites of HUD foreclosure area...,...,𝑞 = Y? . ∃X ∃Y : ((type_of_union_is_had_by_spo...,Which educational institutions have the color ...,𝑞 = Y? . ∃X ∃Y : ((person_has_place_lived_at_l...,What films are from countries where Courtney L...,𝑞 = Y? . ∃X ∃Y : ((participant_was_dated_by_ce...,What award nominations did the celebrities dat...,𝑞 = X? . ∃X : (genre_is_a_genre_of_film('Comed...,What films are either categorized as a comedy-...,𝑞 = Y? . ∃X ∃Y : ((second_level_divisions_are_...,What sports teams are located in areas that ar...
4,𝑞 = X? . ∃X: (award_nominee_has_nominations_fo...,What awards has Christopher Nolan been nominat...,𝑞 = Y? . ∃X ∃Y: (genre_is_a_genre_of_film('Thr...,Who are the producers of Thriller films?,𝑞 = Z? . ∃X ∃Y ∃Z: (event_is_instance_of_recur...,What are the award-winning works that won awar...,𝑞 = X? . ∃X : (educational_institution_has_stu...,Which Rhythm and Blues artists are graduates o...,𝑞 = X? . ∃X: (place_is_had_by_hud_county_place...,What places in Broward County contain Pompano ...,...,𝑞 = Y? . ∃X ∃Y : ((person_has_profession('Walt...,What films released in Hong Kong did not have ...,𝑞 = Y? . ∃X ∃Y : ((military_combatant_group_ha...,What nationalities are associated with individ...,𝑞 = Y? . ∃X ∃Y : ((recurring_event_is_an_insta...,What biography titles on Netflix have won awar...,𝑞 = X? . ∃X : (release_date_s_is_release_date_...,What films have a release date in the United S...,𝑞 = Y? . ∃X ∃Y : ((user_tsegaran_random_has_ta...,What are the taxonomy subjects that either 'Li...

In [111]:
df = pd.read_csv("data/FB15k-237-test.csv")
df.head(5)

/tmp/ipykernel_3646401/2727044545.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/FB15k-237-test.csv")

,1p,1p_FOL,2p,2p_FOL,3p,3p_FOL,2i,2i_FOL,3i,3i_FOL,...,ip_hard_ans,pi_origin,pi_easy_ans,pi_hard_ans,2u_origin,2u_easy_ans,2u_hard_ans,up_origin,up_easy_ans,up_hard_ans
0,"('Wesleyan University', ('educational_institut...",𝑞 = X? . ∃X: (educational_institution_has_stud...,"('Atlantic Ocean', ('adjoining_relationship_is...",𝑞 = Y? . ∃X ∃Y: (adjoining_relationship_is_adj...,"('Bladder cancer', ('disease_has_risk_factors'...",𝑞 = Z? . ∃X ∃Y ∃Z: (disease_has_risk_factors('...,"(('United States of America', ('nationality_is...",𝑞 = X? . ∃X : (nationality_is_held_by_person('...,"(('Bandai Namco Holdings', ('organization_has_...",𝑞 = X? . ∃X: (organization_has_child_which_is_...,...,"{11270, 4842, 7467, 2068, 9174, 4474}","((1327, (30, 405)), (862, (35,)))","{5962, 8619, 8661, 11366}","{8005, 13205}","((4593, (78,)), (1044, (255,)), (-1,))","{8451, 5508, 9476, 2691, 9737, 5771, 2320, 833...","{6680, 13246}","(((2324, (6,)), (569, (2,)), (-1,)), (12,))","{8193, 2572, 525, 6167, 6168, 8220, 28, 7200, ...","{7520, 7040, 6054, 4425, 5744, 8401, 6068}"
1,"('Zookeeper', ('film_film_distributor_relation...",𝑞 = X? . ∃X: (film_film_distributor_relationsh...,"('Pancreatic cancer', ('risk_factors_are_facto...",𝑞 = Y? . ∃X ∃Y: (risk_factors_are_factors_of_d...,"('Library of Congress Classification', ('taxon...",𝑞 = Z? . ∃X ∃Y ∃Z: (taxonomy_entry_is_a_taxono...,"(('James Cagney', ('award_winner_is_winner_of_...",𝑞 = X? . ∃X : (award_winner_is_winner_of_award...,"(('Taraji P. Henson', ('award_nominee_is_an_aw...",𝑞 = X? . ∃X: (award_nominee_is_an_award_nomina...,...,"{11712, 10658, 12451, 13346, 12258, 6917, 9860...","((774, (237, 97)), (592, (49,)))","{8192, 3078, 12, 4109, 4113, 3601, 3603, 12821...","{12801, 1157, 8201, 2571, 12427, 2449, 5394, 1...","((2250, (4,)), (4563, (110,)), (-1,))","{8706, 1539, 6660, 517, 7686, 7687, 4616, 4105...","{4480, 9226, 3723, 7182, 9364, 2838, 3865, 109...","(((1098, (53,)), (3949, (373,)), (-1,)), (272,))","{2561, 5634, 6657, 4104, 6664, 3597, 7695, 16,...","{7550, 2810, 4646, 6091, 7021, 2541, 3696, 110..."
2,"('Dinah Shore', ('student_is_a_graduate_of_edu...",𝑞 = X? . ∃X: (student_is_a_graduate_of_educati...,"('Soap opera', ('genre_is_a_genre_of_tv_progra...",𝑞 = Y? . ∃X ∃Y: (genre_is_a_genre_of_tv_progra...,"('March', ('travel_destination_monthly_climate...",𝑞 = Z? . ∃X ∃Y ∃Z: (travel_destination_monthly...,"(('Dir En Grey', ('artists_are_in_genre',)), (...",𝑞 = X? . ∃X : (artists_are_in_genre('Dir En Gr...,"(('36th Annual Grammy Awards', ('award_ceremon...",𝑞 = X? . ∃X: (award_ceremony_has_awards_presen...,...,"{8224, 2017, 3747, 6344, 1386, 12175, 7314}","((3223, (239, 132)), (2438, (309,)))",{6285},{592},"((3630, (6,)), (871, (35,)), (-1,))","{4107, 12, 2063, 4112, 10257, 16, 6165, 4118, ...","{13312, 5248, 3972, 3463, 5385, 7307, 7948, 25...","(((10381, (341,)), (7343, (35,)), (-1,)), (340,))","{9733, 5638, 12807, 8, 12308, 3606, 4635, 6684...","{2786, 13443, 10274, 4935, 9192, 10922, 238, 1..."
3,"('Hugo Award for Best Short Story', ('award_is...",𝑞 = X? . ∃X: (award_is_an_award_nomination_for...,('Academy Award for Best Actor in a Supporting...,𝑞 = Y? . ∃X ∃Y: (award_category_has_nominees_w...,"('65th Tony Awards', ('award_honor_ceremony_ha...",𝑞 = Z? . ∃X ∃Y ∃Z: (award_honor_ceremony_has_w...,"(('Prime Minister of Canada', ('profession_is_...",𝑞 = X? . ∃X : (profession_is_had_by_person('Pr...,"(('Official Website', ('category_is_a_category...",𝑞 = X? . ∃X: (category_is_a_category_of_webpag...,...,"{1227, 2716, 5679}","((4171, (155, 76)), (7318, (12,)))",NaN,{4046},"((6394, (63,)), (1485, (173,)), (-1,))","{7701, 8215, 1047, 4129, 9251, 5156, 552, 4655...","{7520, 3300, 669, 135, 1255, 8873, 3594, 2378,...","(((3197, (175,)), (1373, (302,)), (-1,)), (188,))","{11746, 14211, 13220, 7014, 12871, 8, 8230, 98...","{12131, 9644, 10942, 4217, 2939, 14237, 12254}"
4,"('Christopher Nolan', ('award_nominee_has_nomi...",𝑞 = X? . ∃X: (award_nominee_has_nominations_fo...,"('Thriller', ('genre_is_a_genre_of_film', 'fil...",𝑞 = Y? . ∃X ∃Y: (genre_is_a_genre_of_film('Thr...,"('14th Academy Awards', ('event_is_instance_of...",𝑞 = Z? . ∃X ∃Y ∃Z: (event_is_instance_of_recur...,"(('Berklee College of Music', ('educational_in...",𝑞 = X? . ∃X : (educational_institution_has_stu...,"(('Pompano Beach', ('place_is_had_by_hud_count...",𝑞 = X? . ∃X: (place_is_had_by_hud_county_place...,...,"{6096, 6724, 9527, 7823}","((3202, (421, 206)), (1130, (4,)))","{7300, 5893, 2699, 1933, 6160, 4379, 1692, 159...",{2150},"((32, (27,)), (23, (23,)), (-1,))","{8193, 8196, 5, 13, 8205, 15, 8211, 8214, 8215...","{2689, 5891, 643, 3845, 7299, 8327, 8068, 9098...","(((235, (236,)), (12148, (236,)), (-1,)), (237,))","{12288, 14336, 0, 6150, 6153, 8202, 14346, 615...","{4353, 8710, 3590, 3464, 1800, 8339, 11923, 14..."

In [115]:
entities = pd.concat([df.iloc[:, 28::3], df.iloc[:, 0::2].iloc[:, :14], text_org.iloc[:, 1::2],df.iloc[:, 29::3], df.iloc[:, 30::3]], axis = 1)
entities

,1p_origin,2p_origin,3p_origin,2i_origin,3i_origin,2in_origin,3in_origin,inp_origin,pin_origin,pni_origin,...,3i_hard_ans,2in_hard_ans,3in_hard_ans,inp_hard_ans,pin_hard_ans,pni_hard_ans,ip_hard_ans,pi_hard_ans,2u_hard_ans,up_hard_ans
0,"(927, (202,))","(965, (117, 267))","(4846, (458, 87, 80))","((32, (97,)), (11188, (39,)))","((13008, (414,)), (4413, (126,)), (9277, (167,)))","((7265, (44,)), (141, (87, -2)))","((1062, (61,)), (90, (69,)), (2948, (53, -2)))","(((570, (84,)), (141, (87, -2))), (85,))","((5918, (445, 267)), (791, (241, -2)))","((5956, (34, 53, -2)), (10567, (23,)))",...,{10153},"{256, 2824, 1026, 2083}","{6914, 7003, 6619}","{1454, 1446, 1287}","{13994, 12723, 10015}","{10121, 6242}","{11270, 4842, 7467, 2068, 9174, 4474}","{8005, 13205}","{6680, 13246}","{7520, 7040, 6054, 4425, 5744, 8401, 6068}"
1,"(3865, (65,))","(6980, (459, 433))","(774, (237, 199, 393))","((5785, (95,)), (3801, (95,)))","((1104, (17,)), (2952, (13,)), (862, (35,)))","((871, (35,)), (393, (35, -2)))","((62, (51,)), (75, (30,)), (1437, (309, -2)))","(((302, (147,)), (3989, (314, -2))), (97,))","((816, (27, 28)), (3324, (428, -2)))","((90, (121, 76, -2)), (742, (64,)))",...,{1103},"{3972, 3463, 7948, 2575, 8975, 3089, 8338, 629...","{11178, 11278}","{5761, 260, 5636, 1670, 3591, 267, 7691, 7053,...",{8832},"{1542, 5105, 2066, 4850, 2393}","{11712, 10658, 12451, 13346, 12258, 6917, 9860...","{12801, 1157, 8201, 2571, 12427, 2449, 5394, 1...","{4480, 9226, 3723, 7182, 9364, 2838, 3865, 109...","{7550, 2810, 4646, 6091, 7021, 2541, 3696, 110..."
2,"(8643, (45,))","(8524, (215, 77))","(7018, (297, 36, 165))","((9182, (41,)), (4936, (41,)))","((2202, (54,)), (985, (184,)), (3020, (321,)))","((32, (301,)), (2982, (227, -2)))","((62, (51,)), (90, (259,)), (4413, (88, -2)))","(((9004, (134,)), (8436, (62, -2))), (215,))","((6205, (458, 100)), (4055, (100, -2)))","((12491, (124, 97, -2)), (215, (35,)))",...,{8112},"{11040, 1697, 1578, 2322, 476}","{742, 2088, 7658, 7788, 7316, 10902, 11191, 87...",{3558},"{8418, 8227, 6691, 7716, 4934, 6663, 9864, 117...","{1024, 5121, 9225, 6682, 12835, 2043, 558, 102...","{8224, 2017, 3747, 6344, 1386, 12175, 7314}",{592},"{13312, 5248, 3972, 3463, 5385, 7307, 7948, 25...","{2786, 13443, 10274, 4935, 9192, 10922, 238, 1..."
3,"(1184, (39,))","(2820, (14, 119))","(10054, (21, 39, 64))","((14496, (35,)), (181, (473,)))","((62, (51,)), (2438, (309,)), (791, (241,)))","((8628, (39,)), (384, (87, -2)))","((2607, (133,)), (32, (97,)), (434, (171, -2)))","(((434, (171,)), (141, (87, -2))), (452,))","((10671, (445, 287)), (10705, (167, -2)))","((434, (171, 45, -2)), (926, (123,)))",...,"{2437, 2055, 2183, 12809, 12300, 12942, 4496, ...",{8716},"{6720, 9730, 5283, 6697, 9371, 9948}","{11067, 11423}","{10247, 8073, 143, 273, 10643, 918, 7191, 2844...","{7296, 12769, 12867, 5980}","{1227, 2716, 5679}",{4046},"{7520, 3300, 669, 135, 1255, 8873, 3594, 2378,...","{12131, 9644, 10942, 4217, 2939, 14237, 12254}"
4,"(2301, (38,))","(658, (63, 168))","(7309, (420, 365, 61))","((972, (44,)), (3068, (40,)))","((5917, (113,)), (7938, (223,)), (7938, (30,)))","((90, (69,)), (1960, (53, -2)))","((23, (23,)), (90, (69,)), (342, (53, -2)))","(((32, (267,)), (90, (439, -2))), (30,))","((1177, (378, 45)), (32, (30, -2)))","((5956, (34, 53, -2)), (2410, (27,)))",...,{5917},"{6147, 5127, 2574, 1045, 5654, 5145, 4125, 772...","{1539, 5127, 2574, 5651, 5654, 6170, 7708, 873...","{8198, 9384, 105, 7464, 9545, 5631, 6223, 8688...","{11587, 6118, 2088, 7083, 10576, 6614, 9562, 2...","{3585, 5892, 1945, 2714, 6308, 2470, 5291, 815...","{6096, 6724, 9527, 7823}",{2150},"{2689, 5891, 643, 3845, 7299, 8327, 8068, 9098...","{4353, 8710, 3590, 3464, 1800, 8339, 11923, 14..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22799,"(692, (96,))",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22800,"(2845, (127,))",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22801,"(1987, (184,))",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22802,"(5959, (86,))",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22803,"(948, (143,))",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
entities.columns

Index(['1p_origin', '2p_origin', '3p_origin', '2i_origin', '3i_origin',
       '2in_origin', '3in_origin', 'inp_origin', 'pin_origin', 'pni_origin',
       'ip_origin', 'pi_origin', '2u_origin', 'up_origin', '1p', '2p', '3p',
       '2i', '3i', '2in', '3in', 'inp', 'pin', 'pni', 'ip', 'pi', '2u', 'up',
       '1p_FOL_NL', '2p_FOL_NL', '3p_FOL_NL', '2i_FOL_NL', '3i_FOL_NL',
       '2in_FOL_NL', '3in_FOL_NL', 'inp_FOL_NL', 'pin_FOL_NL', 'pni_FOL_NL',
       'ip_FOL_NL', 'pi_FOL_NL', '2u_FOL_NL', 'up_FOL_NL', '1p_easy_ans',
       '2p_easy_ans', '3p_easy_ans', '2i_easy_ans', '3i_easy_ans',
       '2in_easy_ans', '3in_easy_ans', 'inp_easy_ans', 'pin_easy_ans',
       'pni_easy_ans', 'ip_easy_ans', 'pi_easy_ans', '2u_easy_ans',
       'up_easy_ans', '1p_hard_ans', '2p_hard_ans', '3p_hard_ans',
       '2i_hard_ans', '3i_hard_ans', '2in_hard_ans', '3in_hard_ans',
       'inp_hard_ans', 'pin_hard_ans', 'pni_hard_ans', 'ip_hard_ans',
       'pi_hard_ans', '2u_hard_ans', 'up_hard_ans'],
      dtype='object')

In [ ]:
'1p_origin', '1p','1p_FOL_NL', '1p_easy_ans','1p_hard_ans'

In [117]:
entities.to_csv("data/all_test.csv", index=False, encoding='utf-8')

In [253]:
df["1p_FOL_NL"][4]

"What is Billy Boyd's profession?"

In [5]:
subs = pd.read_csv("data/llm-8B-237_NL2CL_train.csv")
subs.iloc[:, 1::2]

/tmp/ipykernel_1269493/3387385748.py:1: DtypeWarning: Columns (10,11,12,13,14,15,16,17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  subs = pd.read_csv("data/llm-8B-237_NL2CL_train.csv")

,1p_FOL_NL_CL,2p_FOL_NL_CL,3p_FOL_NL_CL,2i_FOL_NL_CL,3i_FOL_NL_CL,2in_FOL_NL_CL,3in_FOL_NL_CL,inp_FOL_NL_CL,pin_FOL_NL_CL,pni_FOL_NL_CL
0,Who did Howard Hughes participate in a breakup...,Who are the award nominees? / Who nominated by...,What are the award nominations for the categor...,What awards in the category of Literature has ...,What awards have Jennifer Celotta won that Ang...,Who are the actors in Rango who have not dated...,What films featuring Helen Mirren are availabl...,What awards have been won by notable people wi...,What films distributed from Hong Kong genres /...,Which biathlon events were part of the 1948 Wi...
1,What TV programs is Will Arnett a regular cast...,What are the gardening hints related to the tr...,What are the major fields of study for people?...,What genres related to Soft rock is John Foger...,Who has Chris Waddle played for as a goalkeepe...,Who are the actors in Wild at Heart? / Who hav...,What awards were won at the 41st Annual Grammy...,Who are the winners of the 55th Primetime Emmy...,Which athletes from the United States / are no...,Which awards has Ann Curry been nominated for ...
2,What are the prequels to the film National Tre...,What TV programs feature winners of the Daytim...,What are the specializations? / What are the f...,What composers are also guitar instrumentalists?,What locations in the Netherlands adjoin both ...,Who are the people whose cause of death was pn...,What Biographical films are available in the U...,What awards have Manny Coto won? / What are no...,What are larger locations? / Are not divisions...,Which sports teams based in Dallas did not par...
3,What music genres is Bonnie Raitt associated w...,What events involved members of the Empire of ...,What are the ethnicities of the founders? / Wh...,What males have been nominated for multiple aw...,What films have Gary Goetzman produced? / What...,Which artists have been signed to Island Recor...,What films produced by Mark Johnson are availa...,Who were the regular cast members of Downton A...,What awards did Samuel M. Comer's nominees win...,Who are actors from A Beautiful Mind? / Do not...
4,What is Billy Boyd's profession?,In which states or provinces are the headquart...,What is the domestic tuition fee in a specific...,What Library of Congress Classification subjec...,What profession did Warren G. Harding have in ...,Which countries have a unitary system of gover...,Who are Irish American actors? / Who won the P...,In which administrative regions were Bridesmai...,What TV personalities who have made regular ap...,Who are the actors in the film Austin Powers: ...
...,...,...,...,...,...,...,...,...,...,...
149684,What religion does James Cameron have? / Is Ja...,In what languages are they speaking in TV prog...,What are the categories of webpages of artists...,Who has The Rock acted with? / Who is a friend...,What adventure films released in the United St...,NaN,NaN,NaN,NaN,NaN
149685,What awards was the film Bugsy nominated for? ...,What Olympic sports are affiliated with athlet...,What events are involved with entities that to...,What films produced by 20th Century Fox? / Hav...,What states in the United States? / Are in the...,NaN,NaN,NaN,NaN,NaN
149686,What country is the film Wonder Boys from? / W...,What are nominated by the distributors of the ...,What are the notable people? / Who have diseas...,Who is a Guitarist-GB? / Who is a Comedian?,What administrative divisions of the United Ar...,NaN,NaN,NaN,NaN,NaN
149687,Who are Olivia de Havilland's friends? / Who a...,What are the county seats of the counties wher...,What are the symptoms of diseases? / What are ...,What film directors are married?,Who are the male authors born in New Orleans? ...,NaN,NaN,NaN,NaN,NaN
149688,What awards did Shirley Temple win? / Who won ...,What are the categories of webpages? / What ar...,What are the Netflix genres of films? / Where ...,What films from the United States? / Who featu...,What campuses of the University of Nairobi are...,NaN,NaN,NaN,NaN,NaN

In [6]:
df = pd.read_csv("data/all_train.csv")
df

/tmp/ipykernel_1269493/3084850835.py:1: DtypeWarning: Columns (5,6,7,8,9,15,16,17,18,19,25,26,27,28,29,35,36,37,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/all_train.csv")

,1p_origin,2p_origin,3p_origin,2i_origin,3i_origin,2in_origin,3in_origin,inp_origin,pin_origin,pni_origin,...,1p_ans,2p_ans,3p_ans,2i_ans,3i_ans,2in_ans,3in_ans,inp_ans,pin_ans,pni_ans
0,"(3793, (107,))","(4582, (133, 17))","(4526, (95, 364, 39))","((5588, (135,)), (3239, (95,)))","((1730, (35,)), (2669, (7,)), (3587, (17,)))","((135, (13,)), (8594, (154, -2)))","((2263, (12,)), (1080, (57,)), (3352, (4, -2)))","(((1306, (298,)), (954, (49, -2))), (25,))","((2410, (4, 65)), (592, (167, -2)))","((4157, (348, 208, -2)), (389, (131,)))",...,{6381},"{2403, 1221, 137, 1589, 4093}","{10691, 8108, 6764, 4526, 6041, 2748}",{6831},{3659},"{4015, 2479, 5944, 2228, 664}",{5017},"{4736, 3214, 5532, 35, 805, 1194, 9778, 6194, ...","{12388, 11175}","{12105, 1418}"
1,"(6290, (3,))","(3154, (150, 456))","(11341, (12, 5, 225))","((5179, (41,)), (5027, (104,)))","((344, (161,)), (117, (11,)), (5147, (340,)))","((9891, (13,)), (7862, (155, -2)))","((1285, (21,)), (2192, (365,)), (8219, (21, -2)))","(((6805, (21,)), (1641, (15, -2))), (20,))","((32, (97, 80)), (13643, (80, -2)))","((62, (51, 121, -2)), (548, (17,)))",...,{2207},"{6976, 211, 506, 2523, 1277}",{1177},"{264, 1374}","{1495, 3271, 11026, 5717, 2967}","{6569, 6636, 752, 5944, 2810}","{12418, 1284, 3210, 10765, 2201, 2331, 2718, 4...","{9728, 5312, 1994, 4491, 9169, 6805, 1909, 207...","{770, 11522, 2178, 9478, 4102, 646, 3977, 8714...","{547, 4548, 4166, 5895, 5894, 2828, 4493, 4110..."
2,"(3725, (461,))","(7364, (61, 375))","(2273, (341, 34, 362))","((138, (84,)), (1415, (35,)))","((12649, (117,)), (10511, (116,)), (1046, (30,)))","((5983, (100,)), (871, (35, -2)))","((6607, (63,)), (32, (57,)), (1854, (211, -2)))","(((11855, (290,)), (11210, (4, -2))), (60,))","((1529, (320, 31)), (1124, (174, -2)))","((2864, (209, 161, -2)), (5445, (188,)))",...,{9848},"{10471, 5895, 4140, 5140, 2934, 7702, 3993}",{1383},"{7298, 902, 2823, 5773, 8847, 3604, 919, 11544...",{12370},"{9731, 9097, 7178, 2061, 10894, 8719, 5776, 83...","{8704, 6400, 2688, 387, 7937, 5893, 1668, 9865...","{1857, 7969, 1827, 4459, 9358}","{1124, 382}",{13151}
3,"(8965, (41,))","(6187, (263, 176))","(13948, (240, 453, 143))","((141, (87,)), (491, (16,)))","((645, (169,)), (4161, (233,)), (367, (219,)))","((4215, (152,)), (1271, (269, -2)))","((32, (57,)), (6438, (169,)), (4130, (25, -2)))","(((1242, (2,)), (14132, (49, -2))), (48,))","((2477, (16, 6)), (1327, (79, -2)))","((159, (13, 90, -2)), (8556, (2,)))",...,"{7049, 529, 6803, 2581, 7160, 2429}","{4224, 9569, 3653, 8136, 6187, 13626, 2286, 98...","{3929, 5467}","{8803, 7366, 7, 1318, 1319, 5387, 140, 4651, 6...",{1500},"{3073, 7298, 2306, 4868, 9862, 9863, 8718, 859...","{6546, 4155, 3580, 6439}","{13317, 249, 10503, 6605, 11086, 1554, 11827, ...","{2477, 7248, 6486, 9593, 11903}","{3544, 7810}"
4,"(2489, (34,))","(10789, (167, 286))","(372, (226, 88, 332))","((774, (237,)), (11041, (119,)))","((774, (237,)), (12645, (34,)), (8360, (92,)))","((4494, (1,)), (6473, (443, -2)))","((1974, (94,)), (1253, (142,)), (4626, (2, -2)))","(((26, (26,)), (190, (437, -2))), (125,))","((494, (183, 375)), (173, (13, -2)))","((774, (237, 97, -2)), (4448, (13,)))",...,"{1002, 862}",{10320},{90},{8322},{11237},"{1280, 4483, 5001, 3466, 1163, 4875, 6029, 206...",{4000},"{8709, 6535, 9353, 12937, 13073, 8596, 405, 12...","{8705, 7557, 5895, 137, 6537, 7819, 4493, 9357...","{1856, 5783}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149684,"(647, (164,))","(2654, (28, 103))","(8050, (94, 16, 50))","((7202, (13,)), (9201, (91,)))","((32, (27,)), (657, (4,)), (249, (213,)))",NaN,NaN,NaN,NaN,NaN,...,"{2456, 7859}","{11264, 10752, 11266, 4611, 2, 3075, 8203, 461...",{62},{10937},"{9848, 73, 12140}",NaN,NaN,NaN,NaN,NaN
149685,"(3006, (194,))","(3892, (56, 59))","(11046, (263, 326, 177))","((90, (69,)), (441, (173,)))","((2438, (309,)), (5911, (254,)), (32, (411,)))",NaN,NaN,NaN,NaN,NaN,...,{1047},"{5123, 6661, 389, 3337, 1162, 4235, 526, 6286,...","{7139, 12693}","{6400, 772, 7431, 7687, 11399, 7310, 8336, 872...",{582},NaN,NaN,NaN,NaN,NaN
149686,"(2378, (56,))","(5573, (65, 38))","(11957, (86, 459, 298))","((2424, (35,)), (967, (35,)))","((90, (439,)), (208, (271,)), (90, (279,)))",NaN,NaN,NaN,NaN,NaN,...,"{1080, 32, 382, 158}","{1121, 929, 2859, 4304, 1808, 7005}","{3073, 1670, 390, 1798, 6921, 2187, 3085, 9872...","{1157, 4936, 4472, 7772, 10685}",{3573},NaN,NaN,NaN,NaN,NaN
149687,"(9075, (91,))","(9543, (48, 380))","(5787, (86, 459, 433))","((393, (35,)), (434, (171,)))","((141, (87,)), (3414, (39,)), (6489, (49,)))",NaN,NaN,NaN,NaN,NaN,...,{5797},{12592},"{10434, 6500, 9157, 11110, 8837, 9228, 9229, 4...","{8204, 10257, 4118, 2073, 12319, 10271, 4130, ...",{3413},NaN,NaN,NaN,NaN,NaN
149688,"(8881, (95,))","(13619, (240, 50))","(13069, (78, 407, 5))","((3483, (12,)), (32, (57,)))","((2885, (162,)), (13198, (30,)), (2885, (163,)))",NaN,NaN,NaN,NaN,NaN,...,{8178},{62},"{4, 6473, 205, 658, 158}",{12744},{2885},NaN,NaN,NaN,NaN,NaN

검토

In [120]:
pd.read_csv("data/all_test.csv")

/tmp/ipykernel_3646401/3280262144.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,38,39,40,41,43,44,45,46,47,48,49,50,51,52,53,54,55,57,58,59,60,61,62,63,64,65,66,67,68,69) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv("data/all_test.csv")

,1p_origin,2p_origin,3p_origin,2i_origin,3i_origin,2in_origin,3in_origin,inp_origin,pin_origin,pni_origin,...,3i_hard_ans,2in_hard_ans,3in_hard_ans,inp_hard_ans,pin_hard_ans,pni_hard_ans,ip_hard_ans,pi_hard_ans,2u_hard_ans,up_hard_ans
0,"(927, (202,))","(965, (117, 267))","(4846, (458, 87, 80))","((32, (97,)), (11188, (39,)))","((13008, (414,)), (4413, (126,)), (9277, (167,)))","((7265, (44,)), (141, (87, -2)))","((1062, (61,)), (90, (69,)), (2948, (53, -2)))","(((570, (84,)), (141, (87, -2))), (85,))","((5918, (445, 267)), (791, (241, -2)))","((5956, (34, 53, -2)), (10567, (23,)))",...,{10153},"{256, 2824, 1026, 2083}","{6914, 7003, 6619}","{1454, 1446, 1287}","{13994, 12723, 10015}","{10121, 6242}","{11270, 4842, 7467, 2068, 9174, 4474}","{8005, 13205}","{6680, 13246}","{7520, 7040, 6054, 4425, 5744, 8401, 6068}"
1,"(3865, (65,))","(6980, (459, 433))","(774, (237, 199, 393))","((5785, (95,)), (3801, (95,)))","((1104, (17,)), (2952, (13,)), (862, (35,)))","((871, (35,)), (393, (35, -2)))","((62, (51,)), (75, (30,)), (1437, (309, -2)))","(((302, (147,)), (3989, (314, -2))), (97,))","((816, (27, 28)), (3324, (428, -2)))","((90, (121, 76, -2)), (742, (64,)))",...,{1103},"{3972, 3463, 7948, 2575, 8975, 3089, 8338, 629...","{11178, 11278}","{5761, 260, 5636, 1670, 3591, 267, 7691, 7053,...",{8832},"{1542, 5105, 2066, 4850, 2393}","{11712, 10658, 12451, 13346, 12258, 6917, 9860...","{12801, 1157, 8201, 2571, 12427, 2449, 5394, 1...","{4480, 9226, 3723, 7182, 9364, 2838, 3865, 109...","{7550, 2810, 4646, 6091, 7021, 2541, 3696, 110..."
2,"(8643, (45,))","(8524, (215, 77))","(7018, (297, 36, 165))","((9182, (41,)), (4936, (41,)))","((2202, (54,)), (985, (184,)), (3020, (321,)))","((32, (301,)), (2982, (227, -2)))","((62, (51,)), (90, (259,)), (4413, (88, -2)))","(((9004, (134,)), (8436, (62, -2))), (215,))","((6205, (458, 100)), (4055, (100, -2)))","((12491, (124, 97, -2)), (215, (35,)))",...,{8112},"{11040, 1697, 1578, 2322, 476}","{742, 2088, 7658, 7788, 7316, 10902, 11191, 87...",{3558},"{8418, 8227, 6691, 7716, 4934, 6663, 9864, 117...","{1024, 5121, 9225, 6682, 12835, 2043, 558, 102...","{8224, 2017, 3747, 6344, 1386, 12175, 7314}",{592},"{13312, 5248, 3972, 3463, 5385, 7307, 7948, 25...","{2786, 13443, 10274, 4935, 9192, 10922, 238, 1..."
3,"(1184, (39,))","(2820, (14, 119))","(10054, (21, 39, 64))","((14496, (35,)), (181, (473,)))","((62, (51,)), (2438, (309,)), (791, (241,)))","((8628, (39,)), (384, (87, -2)))","((2607, (133,)), (32, (97,)), (434, (171, -2)))","(((434, (171,)), (141, (87, -2))), (452,))","((10671, (445, 287)), (10705, (167, -2)))","((434, (171, 45, -2)), (926, (123,)))",...,"{2437, 2055, 2183, 12809, 12300, 12942, 4496, ...",{8716},"{6720, 9730, 5283, 6697, 9371, 9948}","{11067, 11423}","{10247, 8073, 143, 273, 10643, 918, 7191, 2844...","{7296, 12769, 12867, 5980}","{1227, 2716, 5679}",{4046},"{7520, 3300, 669, 135, 1255, 8873, 3594, 2378,...","{12131, 9644, 10942, 4217, 2939, 14237, 12254}"
4,"(2301, (38,))","(658, (63, 168))","(7309, (420, 365, 61))","((972, (44,)), (3068, (40,)))","((5917, (113,)), (7938, (223,)), (7938, (30,)))","((90, (69,)), (1960, (53, -2)))","((23, (23,)), (90, (69,)), (342, (53, -2)))","(((32, (267,)), (90, (439, -2))), (30,))","((1177, (378, 45)), (32, (30, -2)))","((5956, (34, 53, -2)), (2410, (27,)))",...,{5917},"{6147, 5127, 2574, 1045, 5654, 5145, 4125, 772...","{1539, 5127, 2574, 5651, 5654, 6170, 7708, 873...","{8198, 9384, 105, 7464, 9545, 5631, 6223, 8688...","{11587, 6118, 2088, 7083, 10576, 6614, 9562, 2...","{3585, 5892, 1945, 2714, 6308, 2470, 5291, 815...","{6096, 6724, 9527, 7823}",{2150},"{2689, 5891, 643, 3845, 7299, 8327, 8068, 9098...","{4353, 8710, 3590, 3464, 1800, 8339, 11923, 14..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22799,"(692, (96,))",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22800,"(2845, (127,))",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22801,"(1987, (184,))",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22802,"(5959, (86,))",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22803,"(948, (143,))",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN